-- One table, per your request: everything about a user lives here.
create table if not exists users (
  id                 uuid primary key default gen_random_uuid(),
  device_id          text unique not null,      -- random UUID generated by the extension on install, no PII
  suggestions        jsonb default '[]'::jsonb,  -- last few ad_ids served/prioritized for this user
  clicked_ad_ids     jsonb default '[]'::jsonb,  -- [{ad_id, at}, ...] click history
  impressions_count  integer default 0,
  clicks_count       integer default 0,
  earnings           numeric default 0.0,        -- running balance in USD, zeroed on payout
  paid_out           boolean default false,
  created_at         timestamptz default now()
);

create index if not exists idx_users_device_id on users (device_id);

-- NOTE: this single-table design gives you lifetime totals only.
-- If you want real "today" vs "monthly" charts (not just a running total),
-- you'll eventually want a second append-only events table:
--
-- create table events (
--   id uuid primary key default gen_random_uuid(),
--   device_id text references users(device_id),
--   event_type text check (event_type in ('impression','click')),
--   ad_id text,
--   created_at timestamptz default now()
-- );
--
-- Then "today" = count(*) where created_at::date = current_date,
-- "monthly" = group by date_trunc('day', created_at) for the last 30 days.
-- Skipped for now since you asked for one table — add this later if the
-- admin dashboard needs real day-by-day graphs instead of just totals.

